import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { DRACOLoader } from "three/addons/loaders/DRACOLoader.js";
import RoomAnalyzer from "./room-analyzer/RoomAnalyzer.js";

const $ = (id) => document.getElementById(id);
const API_URL = window.HouseConfig?.apiBaseUrl || location.origin;
const viewer = $("viewer"), loadingScreen = $("loading-screen"), loadingText = $("loading-text"), errorMessage = $("error-message"), roomCard = $("room-card");
const pageParams = new URLSearchParams(location.search);
if (pageParams.has("preview")) document.documentElement.classList.add("preview");

const scene = new THREE.Scene(); scene.background = new THREE.Color(0xf5f0e7); scene.fog = new THREE.Fog(0xf5f0e7, 35, 100);
const camera = new THREE.PerspectiveCamera(45, innerWidth / innerHeight, .05, 500);
let renderer;
try {
  renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: "default", failIfMajorPerformanceCaveat: false });
} catch (error) {
  window.reportViewerBootError?.(`WebGL не запустился: ${error.message}`);
  throw error;
}
renderer.setPixelRatio(Math.min(devicePixelRatio, 1.5)); renderer.setSize(viewer.clientWidth, viewer.clientHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.1; viewer.append(renderer.domElement);
renderer.domElement.addEventListener("webglcontextlost", (event) => { event.preventDefault(); window.reportViewerBootError?.("Браузер потерял WebGL-контекст. Отключите аппаратное ускорение или обновите видеодрайвер."); });
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true; controls.dampingFactor = .06; controls.minPolarAngle = .08; controls.maxPolarAngle = Math.PI / 2.02;
const hemisphere = new THREE.HemisphereLight(0xfff8eb, 0x77746a, 2.35); scene.add(hemisphere); const sun = new THREE.DirectionalLight(0xfff4df, 3); sun.position.set(12, 20, 10); sun.castShadow = true; sun.shadow.mapSize.set(2048, 2048); scene.add(sun); const fill = new THREE.DirectionalLight(0xffdfbd, 1.15); fill.position.set(-10, 8, -10); scene.add(fill);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(200, 200), new THREE.MeshStandardMaterial({ color: 0xf5f0e7, roughness: .95 })); ground.rotation.x = -Math.PI / 2; ground.position.y = -.02; ground.receiveShadow = true; scene.add(ground); const grid = new THREE.GridHelper(100, 100, 0x7b7569, 0x7b7569); grid.position.y = .005; grid.material.opacity = .075; grid.material.transparent = true; scene.add(grid);
function applyTheme(dark) { scene.background.set(dark ? 0x171a16 : 0xf5f0e7); scene.fog.color.set(dark ? 0x171a16 : 0xf5f0e7); ground.material.color.set(dark ? 0x1b1e19 : 0xf5f0e7); grid.material.color?.set(dark ? 0x77786d : 0x7b7569); grid.material.opacity = dark ? .10 : .075; }
applyTheme(document.documentElement.classList.contains("dark")); window.addEventListener("theme-changed", (event) => applyTheme(event.detail.dark));

let house, originalPosition = new THREE.Vector3(), originalTarget = new THREE.Vector3(), cameraAnimation, mixer, activeObjectUrl, activeUpload, roomsAnalysis, roomHighlight;
let wallsVisible = true, pinsVisible = true, brightLighting = true, viewerActive = !(pageParams.get("route") || "").startsWith("/rooms/"), modelRequested = false, animationFrame; const selectable = [], clock = new THREE.Clock(), raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2();
const manager = new THREE.LoadingManager(); const draco = new DRACOLoader(manager); draco.setDecoderPath("./vendor/three/examples/jsm/libs/draco/gltf/"); const loader = new GLTFLoader(manager); loader.setDRACOLoader(draco);

function disposeModel(model) { if (!model) return; model.traverse((object) => { if (!object.isMesh) return; object.geometry?.dispose(); for (const material of Array.isArray(object.material) ? object.material : [object.material]) { if (!material) continue; Object.values(material).forEach((value) => value?.isTexture && value.dispose()); material.dispose(); } }); scene.remove(model); if (roomHighlight) { scene.remove(roomHighlight); roomHighlight.geometry?.dispose(); roomHighlight.material?.dispose(); roomHighlight=null; } selectable.splice(0, selectable.length); mixer?.stopAllAction(); mixer = null; roomsAnalysis = null; }
function prepare(model) { model.traverse((object) => { if (!object.isMesh) return; object.castShadow = object.receiveShadow = true; object.userData.roomAnalyzerVisible=object.visible; selectable.push(object); for (const material of Array.isArray(object.material) ? object.material : [object.material]) { if (material) { material.side = THREE.DoubleSide; if (material.map) material.map.colorSpace = THREE.SRGBColorSpace; } } }); }
function fit(model) { const box = new THREE.Box3().setFromObject(model); if (box.isEmpty()) return; const size = box.getSize(new THREE.Vector3()), center = box.getCenter(new THREE.Vector3()), max = Math.max(size.x, size.y, size.z), distance = max * 1.08; model.position.set(-center.x, -box.min.y, -center.z); camera.near = Math.max(max / 1000, .01); camera.far = max * 100; camera.updateProjectionMatrix(); camera.position.set(distance, distance * .78, distance); controls.target.set(0, size.y * .32, 0); controls.minDistance = max * .15; controls.maxDistance = max * 8; controls.update(); originalPosition.copy(camera.position); originalTarget.copy(controls.target); }
function animate(position, target, duration = 900) { cameraAnimation = { start: performance.now(), duration, from: camera.position.clone(), to: position.clone(), fromTarget: controls.target.clone(), toTarget: target.clone() }; }
function startCameraIntro() { if (pageParams.has("preview") || matchMedia("(prefers-reduced-motion: reduce)").matches) return; const destination = originalPosition.clone(); camera.position.set(-destination.z * 1.18, destination.y * 1.12, destination.x * 1.18); controls.target.copy(originalTarget); controls.update(); animate(destination, originalTarget, 2600); }
function finishModel(model, animations, url) { clearTimeout(window.__viewerReadyTimer); disposeModel(house); if (activeObjectUrl && activeObjectUrl !== url) URL.revokeObjectURL(activeObjectUrl); house = model; prepare(model); fit(model); scene.add(model); if (animations.length) { mixer = new THREE.AnimationMixer(model); animations.forEach((clip) => mixer.clipAction(clip).play()); } loadingScreen.classList.remove("has-error"); loadingScreen.classList.add("hidden"); startCameraIntro(); setTimeout(() => analyzeRooms(model), 20); }
function analyzeRooms(model) {
  const analyzer = new RoomAnalyzer({ mode:"fast", debugRooms:pageParams.get("debugRooms") === "true" || pageParams.get("debugRooms") === "1" });
  roomsAnalysis = analyzer.analyze(model);
  window.RoomarkRooms = roomsAnalysis;
  if (!roomsAnalysis.success) { console.info("RoomAnalyzer:", roomsAnalysis.reason); window.dispatchEvent(new CustomEvent("rooms-analysis-failed", { detail:roomsAnalysis })); return; }
  if (roomsAnalysis.debug?.group) scene.add(roomsAnalysis.debug.group);
  window.AUTO_ROOMS = roomsAnalysis.rooms.map((room) => ({ id:room.id, slug:room.id, name:room.name, area:Number(room.area.toFixed(1)), type:room.type, confidence:room.confidence, automatic:true }));
  const metadata = { ...roomsAnalysis }; delete metadata.debug; try { localStorage.setItem(`roomark:rooms:${initialModelUrl}`, JSON.stringify(metadata)); } catch {}
  window.dispatchEvent(new CustomEvent("rooms-analyzed", { detail:roomsAnalysis }));
  console.table(roomsAnalysis.rooms.map(({ id,name,type,area,confidence,objectIds }) => ({ id,name,type,area:Number(area.toFixed(2)),confidence,objects:objectIds.length })));
  if (pageParams.get("room")) { window.showRoom(pageParams.get("room")); window.focusRoom(pageParams.get("room")); }
}
window.getRoomsMetadata = () => roomsAnalysis ? JSON.parse(JSON.stringify({ ...roomsAnalysis, debug:undefined })) : null;
window.exportRoomsMetadata = () => { const metadata=window.getRoomsMetadata(); if(!metadata)return false; const link=document.createElement("a"); link.href=URL.createObjectURL(new Blob([JSON.stringify(metadata,null,2)],{type:"application/json"})); link.download="rooms.json"; link.click(); setTimeout(()=>URL.revokeObjectURL(link.href),0); return true; };
function loadModel(url, label = "Загрузка проекта...") { loadingScreen.classList.remove("hidden", "has-error"); loadingText.style.display = "block"; document.querySelector(".loader").style.display = "block"; errorMessage.style.display = "none"; loadingText.textContent = label; loader.load(url, ({ scene: model, animations }) => { finishModel(model, animations, url); setUploadStatus("Модель открыта в просмотрщике."); }, undefined, () => showError("Не удалось открыть модель. Проверьте, что файл GLB корректен.")); }
function showError(message) { loadingScreen.classList.add("has-error"); loadingText.style.display = "none"; document.querySelector(".loader").style.display = "none"; errorMessage.textContent = message; errorMessage.style.display = "block"; setUploadStatus(message, true); }
const initialModelUrl = pageParams.get("model") || "./models/house.glb";
function requestInitialModel() { if (modelRequested) return; modelRequested = true; loader.load(initialModelUrl, ({ scene: model, animations }) => finishModel(model, animations, initialModelUrl), undefined, () => showError(pageParams.has("model") ? "Модель комнаты не загрузилась." : "Модель house.glb не найдена. Поместите её в папку models.")); }
if (viewerActive) requestInitialModel(); else loadingScreen.classList.add("hidden");

$("home-button").onclick = () => animate(originalPosition, originalTarget);
$("top-button").onclick = () => { if (!house) return; const size = new THREE.Box3().setFromObject(house).getSize(new THREE.Vector3()), distance = Math.max(size.x, size.z); animate(new THREE.Vector3(.001, distance * 1.7, .001), new THREE.Vector3()); };
$("rotate-button").onclick = (event) => { controls.autoRotate = !controls.autoRotate; controls.autoRotateSpeed = 1; event.currentTarget.classList.toggle("active", controls.autoRotate); };
$("walls-button").onclick = (event) => { wallsVisible = !wallsVisible; house?.traverse((object) => { if (object.isMesh && (object.userData.ifcType === "IfcWall" || object.name.toLowerCase().includes("wall") || object.name.toLowerCase().includes("стена"))) object.visible = wallsVisible; }); event.currentTarget.classList.toggle("active", !wallsVisible); };
$("pins-button").onclick = (event) => { pinsVisible = !pinsVisible; noteLayer.hidden = !pinsVisible; event.currentTarget.classList.toggle("active", !pinsVisible); };
$("lighting-button").onclick = (event) => { brightLighting = !brightLighting; hemisphere.intensity = brightLighting ? 2.35 : 1.05; sun.intensity = brightLighting ? 3 : 1.25; fill.intensity = brightLighting ? 1.15 : .45; renderer.toneMappingExposure = brightLighting ? 1.1 : .82; event.currentTarget.classList.toggle("active", !brightLighting); };
$("screenshot-button").onclick = () => { renderer.render(scene, camera); const link = document.createElement("a"); link.download = `roomark-${new Date().toISOString().slice(0, 10)}.png`; link.href = renderer.domElement.toDataURL("image/png"); link.click(); };

const fileInput = $("model-file-input"), dropzone = $("upload-dropzone"), progress = $("upload-progress"), progressBar = progress.firstElementChild;
const setUploadStatus = (text, error = false) => { $("upload-status").textContent = text; $("upload-status").style.color = error ? "var(--color-danger)" : ""; };
const showProgress = (value, indeterminate = false) => { progress.hidden = false; progress.classList.toggle("indeterminate", indeterminate); progressBar.style.width = `${value}%`; };
function describe(file) { return `${file.name} — ${(file.size / 1024 / 1024).toFixed(1)} МБ`; }
async function selectModel(file) { if (!file) return; const extension = file.name.split(".").pop().toLowerCase(); $("upload-file-info").textContent = describe(file); if (["pla", "pln"].includes(extension)) return setUploadStatus("Экспортируйте проект из Archicad в IFC, затем загрузите IFC на сайт.", true); if (!["ifc", "glb", "gltf"].includes(extension)) return setUploadStatus("Выберите файл IFC, GLB или GLTF.", true); if (extension === "gltf") return setUploadStatus("Для модели с отдельными ресурсами используйте единый файл GLB.", true); if (extension === "glb") { activeObjectUrl = URL.createObjectURL(file); window.showApartment?.(); window.setViewerActive?.(true); loadModel(activeObjectUrl); return; } uploadIfc(file); }
function uploadIfc(file) { const password = $("upload-password").value; if (!password) return setUploadStatus("Введите пароль для загрузки.", true); activeUpload = new XMLHttpRequest(); showProgress(0); $("upload-cancel").hidden = false; setUploadStatus("Загрузка файла"); activeUpload.open("POST", `${API_URL}/api/models`); activeUpload.setRequestHeader("X-Upload-Password", password); activeUpload.upload.onprogress = (event) => { if (event.lengthComputable) { const percent = Math.round(event.loaded / event.total * 100); showProgress(percent); setUploadStatus(`Загрузка файла: ${percent}%`); } }; activeUpload.onerror = () => finishUpload("Не удалось связаться с сервером конвертации.", true); activeUpload.onabort = () => finishUpload("Загрузка отменена.", true); activeUpload.onload = () => { if (activeUpload.status >= 200 && activeUpload.status < 300) { try { pollJob(JSON.parse(activeUpload.responseText).jobId); } catch { finishUpload("Сервер вернул некорректный ответ.", true); } } else { try { finishUpload(JSON.parse(activeUpload.responseText).error || "Не удалось загрузить IFC.", true); } catch { finishUpload("Не удалось загрузить IFC.", true); } } }; const data = new FormData(); data.append("model", file); activeUpload.send(data); }
async function pollJob(jobId) { showProgress(0, true); const timer = setInterval(async () => { try { const response = await fetch(`${API_URL}/api/models/${encodeURIComponent(jobId)}/status`); const job = await response.json(); setUploadStatus(job.stage || "Обработка IFC"); if (job.status === "ready") { clearInterval(timer); progress.hidden = true; $("upload-cancel").hidden = true; window.showApartment?.(); window.setViewerActive?.(true); loadModel(`${API_URL}${job.modelUrl}`); } else if (job.status === "failed") { clearInterval(timer); finishUpload(job.error || "Не удалось преобразовать IFC.", true); } } catch { clearInterval(timer); finishUpload("Не удалось получить статус обработки.", true); } }, 1000); }
function finishUpload(message, error) { progress.hidden = true; $("upload-cancel").hidden = true; activeUpload = null; setUploadStatus(message, error); }
$("upload-button").onclick = () => { fileInput.accept = ".ifc,.glb,.gltf,.pla,.pln"; fileInput.value = ""; fileInput.click(); }; fileInput.onchange = () => selectModel(fileInput.files[0]); $("upload-cancel").onclick = () => activeUpload?.abort(); ["dragenter", "dragover"].forEach((type) => dropzone.addEventListener(type, (event) => { event.preventDefault(); dropzone.classList.add("dragging"); })); ["dragleave", "drop"].forEach((type) => dropzone.addEventListener(type, (event) => { event.preventDefault(); dropzone.classList.remove("dragging"); })); dropzone.addEventListener("drop", (event) => selectModel(event.dataTransfer.files[0]));
$("document-glb-upload").onclick = () => { fileInput.accept = ".glb,model/gltf-binary"; fileInput.value = ""; fileInput.click(); };
$("document-ifc-upload").onclick = () => { fileInput.accept = ".ifc,application/octet-stream"; fileInput.value = ""; fileInput.click(); };

renderer.domElement.addEventListener("pointerdown", (event) => { const bounds = renderer.domElement.getBoundingClientRect(); pointer.set((event.clientX - bounds.left) / bounds.width * 2 - 1, -(event.clientY - bounds.top) / bounds.height * 2 + 1); raycaster.setFromCamera(pointer, camera); const hit = raycaster.intersectObjects(selectable, false)[0]; if (!hit) return roomCard.classList.remove("visible"); const data = hit.object.userData; if (data.ifcType !== "IfcSpace" && !data.title && !data.area) return roomCard.classList.remove("visible"); $("room-name").textContent = data.name || data.title || hit.object.name || "Помещение"; $("room-description").textContent = [data.area && `Площадь: ${data.area} м²`, data.ifcType].filter(Boolean).join(". "); roomCard.style.left = `${event.clientX}px`; roomCard.style.top = `${event.clientY}px`; roomCard.classList.add("visible"); });
const noteLayer = document.createElement("div"); noteLayer.className = "model-note-layer"; noteLayer.hidden = pageParams.has("preview"); viewer.append(noteLayer); let modelNotes = [];
let activeModelNoteId = null;
function renderModelNotes() { noteLayer.innerHTML = modelNotes.map((note,index) => `<button class="model-note-pin" type="button" data-model-note="${note.id}" aria-label="Открыть замечание ${index + 1}"><span>${index + 1}</span></button>`).join(""); const note=modelNotes.find(({id})=>id===activeModelNoteId); if(note) { const card=document.createElement("article"), text=document.createElement("p"), date=document.createElement("small"); card.className="model-note-popover"; text.textContent=note.text; date.textContent=new Date(note.createdAt).toLocaleString("ru"); card.append(text,date); noteLayer.append(card); } }
async function loadModelNotes() { try { const response = await fetch(`${API_URL}/api/notes`, { cache:"no-store" }); modelNotes = response.ok ? await response.json() : []; renderModelNotes(); } catch { modelNotes = []; renderModelNotes(); } }
noteLayer.addEventListener("click", (event) => { const pin = event.target.closest("[data-model-note]"); if (!pin) return; event.stopPropagation(); activeModelNoteId = activeModelNoteId === pin.dataset.modelNote ? null : pin.dataset.modelNote; renderModelNotes(); positionModelNotes(); });
if (!pageParams.has("preview")) { loadModelNotes(); window.addEventListener("notes-changed", loadModelNotes); }
function resolveRoom(roomKey) { if (!roomsAnalysis?.success) return null; const key=String(roomKey||"").toLowerCase(), aliases={kitchen:/kitchen|living|кух|гостин/i,bedroom:/bed|спаль/i,bathroom:/bath|wc|сануз|ванн/i,hall:/hall|corridor|прихож|коридор/i,terrace:/terrace|balcony|террас|балкон/i}; return roomsAnalysis.rooms.find((room)=>room.id===roomKey||room.type===roomKey||room.name.toLowerCase()===key)||roomsAnalysis.rooms.find((room)=>aliases[key]?.test(`${room.type} ${room.name}`)); }
window.showAllRooms = () => { if (!house) return; house.traverse((object) => { if (object.isMesh) object.visible = object.userData.roomAnalyzerVisible !== false; }); if (roomHighlight) roomHighlight.visible=false; };
window.showRoom = (roomKey) => { const room=resolveRoom(roomKey); if (!house || !room) return false; house.traverse((object) => { if (!object.isMesh) return; if (object.userData.roomAnalyzerVisible === undefined) object.userData.roomAnalyzerVisible=object.visible; const ids=object.userData.roomIds||[]; object.visible=ids.includes(room.id); }); window.highlightRoom(room.id); return true; };
window.focusRoom = (roomKey) => { const room=resolveRoom(roomKey); if (!house) return; if (!room) return animate(originalPosition,originalTarget); const min=new THREE.Vector3(room.boundingBox.min.x,room.floorY,room.boundingBox.min.z),max=new THREE.Vector3(room.boundingBox.max.x,room.ceilingY,room.boundingBox.max.z),box=new THREE.Box3(min,max),size=box.getSize(new THREE.Vector3()),target=box.getCenter(new THREE.Vector3()),fov=THREE.MathUtils.degToRad(camera.fov),fitHeight=size.y/(2*Math.tan(fov/2)),fitWidth=size.x/(2*Math.tan(fov/2)*camera.aspect),distance=Math.max(fitHeight,fitWidth,size.z)*1.45,direction=new THREE.Vector3(1,.72,1).normalize(); animate(target.clone().addScaledVector(direction,distance),target,1300); };
window.highlightRoom = (roomKey) => { const room=resolveRoom(roomKey); if (!room) return false; if (roomHighlight) { scene.remove(roomHighlight); roomHighlight.geometry.dispose(); roomHighlight.material.dispose(); } const shape=new THREE.Shape(room.polygon.map(([x,z])=>new THREE.Vector2(x,z))); roomHighlight=new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshBasicMaterial({color:0xf2a31b,transparent:true,opacity:.18,depthWrite:false,side:THREE.DoubleSide})); roomHighlight.rotation.x=Math.PI/2; roomHighlight.position.y=room.floorY+.025; roomHighlight.name=`RoomHighlight_${room.id}`; scene.add(roomHighlight); return true; };
addEventListener("resize", () => { camera.aspect = viewer.clientWidth / viewer.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(viewer.clientWidth, viewer.clientHeight, false); });
function positionModelNotes() { if (!house || !pinsVisible) return; const card=noteLayer.querySelector(".model-note-popover"), box = new THREE.Box3().setFromObject(house), size = box.getSize(new THREE.Vector3()); [...noteLayer.querySelectorAll("[data-model-note]")].forEach((pin,index) => { const note = modelNotes[index], position = note?.position || { x:.5,y:.55,z:.5 }, point = new THREE.Vector3(box.min.x + size.x * position.x, box.min.y + size.y * position.y, box.min.z + size.z * position.z).project(camera); const visible = point.z > -1 && point.z < 1; pin.hidden = !visible; pin.style.left = `${(point.x + 1) * 50}%`; pin.style.top = `${(1 - point.y) * 50}%`; if (card && note.id === activeModelNoteId) { card.hidden=!visible; card.style.left=pin.style.left; card.style.top=pin.style.top; } }); }
function render() { if (!viewerActive) return; animationFrame = requestAnimationFrame(render); if (mixer) mixer.update(clock.getDelta()); if (cameraAnimation) { const progress = Math.min((performance.now() - cameraAnimation.start) / cameraAnimation.duration, 1), eased = 1 - (1 - progress) ** 3; camera.position.lerpVectors(cameraAnimation.from, cameraAnimation.to, eased); controls.target.lerpVectors(cameraAnimation.fromTarget, cameraAnimation.toTarget, eased); if (progress === 1) cameraAnimation = null; } controls.update(); renderer.render(scene, camera); positionModelNotes(); }
window.setViewerActive = (active) => { if (viewerActive === active) return; viewerActive = active; if (!active) { cancelAnimationFrame(animationFrame); controls.autoRotate = false; clock.stop(); return; } requestInitialModel(); clock.start(); window.dispatchEvent(new Event("resize")); render(); };
if (viewerActive) render();
