import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { DRACOLoader } from "three/addons/loaders/DRACOLoader.js";

const $ = (id) => document.getElementById(id);
const API_URL = window.MODEL_API_URL || "http://localhost:3001";
const viewer = $("viewer"), loadingScreen = $("loading-screen"), loadingText = $("loading-text"), errorMessage = $("error-message"), roomCard = $("room-card");
const pageParams = new URLSearchParams(location.search);
if (pageParams.has("preview")) document.documentElement.classList.add("preview");

const scene = new THREE.Scene(); scene.background = new THREE.Color(0xf1f5f9); scene.fog = new THREE.Fog(0xf1f5f9, 35, 100);
const camera = new THREE.PerspectiveCamera(45, innerWidth / innerHeight, .05, 500);
const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: "high-performance" });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(viewer.clientWidth, viewer.clientHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.1; viewer.append(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true; controls.dampingFactor = .06; controls.minPolarAngle = .08; controls.maxPolarAngle = Math.PI / 2.02;
const hemisphere = new THREE.HemisphereLight(0xffffff, 0x718096, 2.35); scene.add(hemisphere); const sun = new THREE.DirectionalLight(0xffffff, 3); sun.position.set(12, 20, 10); sun.castShadow = true; sun.shadow.mapSize.set(2048, 2048); scene.add(sun); const fill = new THREE.DirectionalLight(0xcfe1ff, 1.15); fill.position.set(-10, 8, -10); scene.add(fill);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(200, 200), new THREE.MeshStandardMaterial({ color: 0xe7edf4, roughness: .95 })); ground.rotation.x = -Math.PI / 2; ground.position.y = -.02; ground.receiveShadow = true; scene.add(ground); const grid = new THREE.GridHelper(100, 100, 0xb6c2d0, 0xd5dde7); grid.position.y = .005; grid.material.opacity = .2; grid.material.transparent = true; scene.add(grid);

let house, originalPosition = new THREE.Vector3(), originalTarget = new THREE.Vector3(), cameraAnimation, mixer, activeObjectUrl, activeUpload;
let wallsVisible = true, brightLighting = true; const selectable = [], clock = new THREE.Clock(), raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2();
const manager = new THREE.LoadingManager(); const draco = new DRACOLoader(manager); draco.setDecoderPath("https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/libs/draco/"); const loader = new GLTFLoader(manager); loader.setDRACOLoader(draco);

function disposeModel(model) { if (!model) return; model.traverse((object) => { if (!object.isMesh) return; object.geometry?.dispose(); for (const material of Array.isArray(object.material) ? object.material : [object.material]) { if (!material) continue; Object.values(material).forEach((value) => value?.isTexture && value.dispose()); material.dispose(); } }); scene.remove(model); selectable.splice(0, selectable.length); mixer?.stopAllAction(); mixer = null; }
function prepare(model) { model.traverse((object) => { if (!object.isMesh) return; object.castShadow = object.receiveShadow = true; selectable.push(object); for (const material of Array.isArray(object.material) ? object.material : [object.material]) { if (material) { material.side = THREE.DoubleSide; if (material.map) material.map.colorSpace = THREE.SRGBColorSpace; } } }); }
function fit(model) { const box = new THREE.Box3().setFromObject(model); if (box.isEmpty()) return; const size = box.getSize(new THREE.Vector3()), center = box.getCenter(new THREE.Vector3()), max = Math.max(size.x, size.y, size.z), distance = max * 1.65; model.position.set(-center.x, -box.min.y, -center.z); camera.near = Math.max(max / 1000, .01); camera.far = max * 100; camera.updateProjectionMatrix(); camera.position.set(distance, distance * .72, distance); controls.target.set(0, size.y * .35, 0); controls.minDistance = max * .15; controls.maxDistance = max * 8; controls.update(); originalPosition.copy(camera.position); originalTarget.copy(controls.target); }
function animate(position, target, duration = 900) { cameraAnimation = { start: performance.now(), duration, from: camera.position.clone(), to: position.clone(), fromTarget: controls.target.clone(), toTarget: target.clone() }; }
function startCameraIntro() { if (pageParams.has("preview") || matchMedia("(prefers-reduced-motion: reduce)").matches) return; const destination = originalPosition.clone(); camera.position.set(-destination.z * 1.18, destination.y * 1.12, destination.x * 1.18); controls.target.copy(originalTarget); controls.update(); animate(destination, originalTarget, 2600); }
function finishModel(model, animations, url) { disposeModel(house); if (activeObjectUrl && activeObjectUrl !== url) URL.revokeObjectURL(activeObjectUrl); house = model; prepare(model); fit(model); scene.add(model); if (animations.length) { mixer = new THREE.AnimationMixer(model); animations.forEach((clip) => mixer.clipAction(clip).play()); } loadingScreen.classList.add("hidden"); startCameraIntro(); if (pageParams.get("room")) setTimeout(() => window.focusRoom?.(pageParams.get("room")), 80); }
function loadModel(url, label = "Загрузка проекта...") { loadingScreen.classList.remove("hidden"); loadingText.style.display = "block"; document.querySelector(".loader").style.display = "block"; errorMessage.style.display = "none"; loadingText.textContent = label; loader.load(url, ({ scene: model, animations }) => { finishModel(model, animations, url); setUploadStatus("Модель открыта в просмотрщике."); }, undefined, () => showError("Не удалось открыть модель. Проверьте, что файл GLB корректен.")); }
function showError(message) { loadingText.style.display = "none"; document.querySelector(".loader").style.display = "none"; errorMessage.textContent = message; errorMessage.style.display = "block"; setUploadStatus(message, true); }
const initialModelUrl = pageParams.get("model") || "./models/house.glb";
loader.load(initialModelUrl, ({ scene: model, animations }) => finishModel(model, animations, initialModelUrl), undefined, () => showError(pageParams.has("model") ? "Модель комнаты не загрузилась." : "Модель house.glb не найдена. Поместите её в папку models."));

$("home-button").onclick = () => animate(originalPosition, originalTarget);
$("top-button").onclick = () => { if (!house) return; const size = new THREE.Box3().setFromObject(house).getSize(new THREE.Vector3()), distance = Math.max(size.x, size.z); animate(new THREE.Vector3(.001, distance * 1.7, .001), new THREE.Vector3()); };
$("rotate-button").onclick = (event) => { controls.autoRotate = !controls.autoRotate; controls.autoRotateSpeed = 1; event.currentTarget.classList.toggle("active", controls.autoRotate); };
$("walls-button").onclick = (event) => { wallsVisible = !wallsVisible; house?.traverse((object) => { if (object.isMesh && (object.userData.ifcType === "IfcWall" || object.name.toLowerCase().includes("wall") || object.name.toLowerCase().includes("стена"))) object.visible = wallsVisible; }); event.currentTarget.classList.toggle("active", !wallsVisible); };
$("lighting-button").onclick = (event) => { brightLighting = !brightLighting; hemisphere.intensity = brightLighting ? 2.35 : 1.05; sun.intensity = brightLighting ? 3 : 1.25; fill.intensity = brightLighting ? 1.15 : .45; renderer.toneMappingExposure = brightLighting ? 1.1 : .82; event.currentTarget.classList.toggle("active", !brightLighting); };
$("screenshot-button").onclick = () => { renderer.render(scene, camera); const link = document.createElement("a"); link.download = `house-reviewer-${new Date().toISOString().slice(0, 10)}.png`; link.href = renderer.domElement.toDataURL("image/png"); link.click(); };
$("fullscreen-button").onclick = () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen();

const fileInput = $("model-file-input"), dropzone = $("upload-dropzone"), progress = $("upload-progress"), progressBar = progress.firstElementChild;
const setUploadStatus = (text, error = false) => { $("upload-status").textContent = text; $("upload-status").style.color = error ? "#dc2626" : ""; };
const showProgress = (value, indeterminate = false) => { progress.hidden = false; progress.classList.toggle("indeterminate", indeterminate); progressBar.style.width = `${value}%`; };
function describe(file) { return `${file.name} — ${(file.size / 1024 / 1024).toFixed(1)} МБ`; }
async function selectModel(file) { if (!file) return; const extension = file.name.split(".").pop().toLowerCase(); $("upload-file-info").textContent = describe(file); if (["pla", "pln"].includes(extension)) return setUploadStatus("Экспортируйте проект из Archicad в IFC, затем загрузите IFC на сайт.", true); if (!["ifc", "glb", "gltf"].includes(extension)) return setUploadStatus("Выберите файл IFC, GLB или GLTF.", true); if (extension === "gltf") return setUploadStatus("Для модели с отдельными ресурсами используйте единый файл GLB.", true); if (extension === "glb") { activeObjectUrl = URL.createObjectURL(file); document.querySelector('[data-mode="3d"]')?.click(); loadModel(activeObjectUrl); return; } uploadIfc(file); }
function uploadIfc(file) { const password = $("upload-password").value; if (!password) return setUploadStatus("Введите пароль для загрузки.", true); activeUpload = new XMLHttpRequest(); showProgress(0); $("upload-cancel").hidden = false; setUploadStatus("Загрузка файла"); activeUpload.open("POST", `${API_URL}/api/models`); activeUpload.setRequestHeader("X-Upload-Password", password); activeUpload.upload.onprogress = (event) => { if (event.lengthComputable) { const percent = Math.round(event.loaded / event.total * 100); showProgress(percent); setUploadStatus(`Загрузка файла: ${percent}%`); } }; activeUpload.onerror = () => finishUpload("Не удалось связаться с сервером конвертации.", true); activeUpload.onabort = () => finishUpload("Загрузка отменена.", true); activeUpload.onload = () => { if (activeUpload.status >= 200 && activeUpload.status < 300) { try { pollJob(JSON.parse(activeUpload.responseText).jobId); } catch { finishUpload("Сервер вернул некорректный ответ.", true); } } else { try { finishUpload(JSON.parse(activeUpload.responseText).error || "Не удалось загрузить IFC.", true); } catch { finishUpload("Не удалось загрузить IFC.", true); } } }; const data = new FormData(); data.append("model", file); activeUpload.send(data); }
async function pollJob(jobId) { showProgress(0, true); const timer = setInterval(async () => { try { const response = await fetch(`${API_URL}/api/models/${encodeURIComponent(jobId)}/status`); const job = await response.json(); setUploadStatus(job.stage || "Обработка IFC"); if (job.status === "ready") { clearInterval(timer); progress.hidden = true; $("upload-cancel").hidden = true; document.querySelector('[data-mode="3d"]')?.click(); loadModel(`${API_URL}${job.modelUrl}`); } else if (job.status === "failed") { clearInterval(timer); finishUpload(job.error || "Не удалось преобразовать IFC.", true); } } catch { clearInterval(timer); finishUpload("Не удалось получить статус обработки.", true); } }, 1000); }
function finishUpload(message, error) { progress.hidden = true; $("upload-cancel").hidden = true; activeUpload = null; setUploadStatus(message, error); }
$("upload-button").onclick = () => { fileInput.accept = ".ifc,.glb,.gltf,.pla,.pln"; fileInput.value = ""; fileInput.click(); }; fileInput.onchange = () => selectModel(fileInput.files[0]); $("upload-cancel").onclick = () => activeUpload?.abort(); ["dragenter", "dragover"].forEach((type) => dropzone.addEventListener(type, (event) => { event.preventDefault(); dropzone.classList.add("dragging"); })); ["dragleave", "drop"].forEach((type) => dropzone.addEventListener(type, (event) => { event.preventDefault(); dropzone.classList.remove("dragging"); })); dropzone.addEventListener("drop", (event) => selectModel(event.dataTransfer.files[0]));
$("document-glb-upload").onclick = () => { fileInput.accept = ".glb,model/gltf-binary"; fileInput.value = ""; fileInput.click(); };
$("document-ifc-upload").onclick = () => { fileInput.accept = ".ifc,application/octet-stream"; fileInput.value = ""; fileInput.click(); };

renderer.domElement.addEventListener("pointerdown", (event) => { const bounds = renderer.domElement.getBoundingClientRect(); pointer.set((event.clientX - bounds.left) / bounds.width * 2 - 1, -(event.clientY - bounds.top) / bounds.height * 2 + 1); raycaster.setFromCamera(pointer, camera); const hit = raycaster.intersectObjects(selectable, false)[0]; if (!hit) return roomCard.classList.remove("visible"); const data = hit.object.userData; if (data.ifcType !== "IfcSpace" && !data.title && !data.area) return roomCard.classList.remove("visible"); $("room-name").textContent = data.name || data.title || hit.object.name || "Помещение"; $("room-description").textContent = [data.area && `Площадь: ${data.area} м²`, data.ifcType].filter(Boolean).join(". "); roomCard.style.left = `${event.clientX}px`; roomCard.style.top = `${event.clientY}px`; roomCard.classList.add("visible"); });
window.focusRoom = (roomKey) => { if (!house) return; const aliases = { kitchen: /kitchen|living|кух|гостин/i, bedroom: /bed|спаль/i, bathroom: /bath|wc|сануз|ванн/i, hall: /hall|corridor|прихож|коридор/i, terrace: /terrace|balcony|террас|балкон/i }, matched = selectable.filter((object) => aliases[roomKey]?.test(`${object.name} ${object.userData?.name || ""} ${object.userData?.title || ""}`)); const houseSize = new THREE.Box3().setFromObject(house).getSize(new THREE.Vector3()); let target; if (matched.length) { const roomBox = new THREE.Box3(); matched.forEach((object) => roomBox.union(new THREE.Box3().setFromObject(object))); target = roomBox.getCenter(new THREE.Vector3()); } else { const positions = { kitchen: [.18, .18], bedroom: [-.2, .18], bathroom: [-.12, -.12], hall: [.05, 0], terrace: [.28, -.18] }, [x, z] = positions[roomKey] || [0, 0]; target = new THREE.Vector3(x * houseSize.x, Math.max(houseSize.y * .28, .5), z * houseSize.z); } const distance = Math.max(houseSize.x, houseSize.z) * .72; animate(new THREE.Vector3(target.x + distance, target.y + distance * .62, target.z + distance), target, 1500); };
addEventListener("resize", () => { camera.aspect = viewer.clientWidth / viewer.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(viewer.clientWidth, viewer.clientHeight, false); });
function render() { requestAnimationFrame(render); if (mixer) mixer.update(clock.getDelta()); if (cameraAnimation) { const progress = Math.min((performance.now() - cameraAnimation.start) / cameraAnimation.duration, 1), eased = 1 - (1 - progress) ** 3; camera.position.lerpVectors(cameraAnimation.from, cameraAnimation.to, eased); controls.target.lerpVectors(cameraAnimation.fromTarget, cameraAnimation.toTarget, eased); if (progress === 1) cameraAnimation = null; } controls.update(); renderer.render(scene, camera); } render();
