import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { DRACOLoader } from "three/addons/loaders/DRACOLoader.js";

const $ = (id) => document.getElementById(id);
const API_URL = window.MODEL_API_URL || "http://localhost:3001";
const viewer = $("viewer"), loadingScreen = $("loading-screen"), loadingText = $("loading-text"), errorMessage = $("error-message"), roomCard = $("room-card");
const pageParams = new URLSearchParams(location.search);
if (pageParams.has("preview")) document.documentElement.classList.add("preview");

const scene = new THREE.Scene(); scene.background = new THREE.Color(0xdce7f2); scene.fog = new THREE.Fog(0xdce7f2, 35, 100);
const camera = new THREE.PerspectiveCamera(45, innerWidth / innerHeight, .05, 500);
const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: "high-performance" });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(viewer.clientWidth, viewer.clientHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.1; viewer.append(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true; controls.dampingFactor = .06; controls.minPolarAngle = .08; controls.maxPolarAngle = Math.PI / 2.02;
scene.add(new THREE.HemisphereLight(0xffffff, 0x4d6276, 2.2)); const sun = new THREE.DirectionalLight(0xffffff, 3); sun.position.set(12, 20, 10); sun.castShadow = true; sun.shadow.mapSize.set(2048, 2048); scene.add(sun); const fill = new THREE.DirectionalLight(0xbfd6ff, 1); fill.position.set(-10, 8, -10); scene.add(fill);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(200, 200), new THREE.MeshStandardMaterial({ color: 0xc8d5e3, roughness: .95 })); ground.rotation.x = -Math.PI / 2; ground.position.y = -.02; ground.receiveShadow = true; scene.add(ground); const grid = new THREE.GridHelper(100, 100, 0x8ca0b3, 0xb5c4d1); grid.position.y = .005; grid.material.opacity = .18; grid.material.transparent = true; scene.add(grid);

let house, originalPosition = new THREE.Vector3(), originalTarget = new THREE.Vector3(), cameraAnimation, mixer, activeObjectUrl, activeUpload;
let wallsVisible = true; const selectable = [], clock = new THREE.Clock(), raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2();
const manager = new THREE.LoadingManager(); const draco = new DRACOLoader(manager); draco.setDecoderPath("https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/libs/draco/"); const loader = new GLTFLoader(manager); loader.setDRACOLoader(draco);

function disposeModel(model) { if (!model) return; model.traverse((o) => { if (!o.isMesh) return; o.geometry?.dispose(); for (const m of Array.isArray(o.material) ? o.material : [o.material]) { if (!m) continue; Object.values(m).forEach((v) => v?.isTexture && v.dispose()); m.dispose(); } }); scene.remove(model); selectable.splice(0, selectable.length); mixer?.stopAllAction(); mixer = null; }
function prepare(model) { model.traverse((o) => { if (!o.isMesh) return; o.castShadow = o.receiveShadow = true; selectable.push(o); for (const m of Array.isArray(o.material) ? o.material : [o.material]) { if (m) { m.side = THREE.DoubleSide; if (m.map) m.map.colorSpace = THREE.SRGBColorSpace; } } }); }
function fit(model) { const box = new THREE.Box3().setFromObject(model); if (box.isEmpty()) return; const size = box.getSize(new THREE.Vector3()), center = box.getCenter(new THREE.Vector3()), max = Math.max(size.x, size.y, size.z), d = max * 1.65; model.position.set(-center.x, -box.min.y, -center.z); camera.near = Math.max(max / 1000, .01); camera.far = max * 100; camera.updateProjectionMatrix(); camera.position.set(d, d * .72, d); controls.target.set(0, size.y * .35, 0); controls.minDistance = max * .15; controls.maxDistance = max * 8; controls.update(); originalPosition.copy(camera.position); originalTarget.copy(controls.target); }
function loadModel(url, label = "Загрузка в просмотрщик") { loadingScreen.classList.remove("hidden"); loadingText.style.display = "block"; document.querySelector(".loader").style.display = "block"; errorMessage.style.display = "none"; loadingText.textContent = label; loader.load(url, ({ scene: model, animations }) => { disposeModel(house); if (activeObjectUrl && activeObjectUrl !== url) URL.revokeObjectURL(activeObjectUrl); house = model; prepare(model); fit(model); scene.add(model); if (animations.length) { mixer = new THREE.AnimationMixer(model); animations.forEach((c) => mixer.clipAction(c).play()); } loadingScreen.classList.add("hidden"); setUploadStatus("Модель открыта в просмотрщике."); }, undefined, () => showError("Не удалось открыть модель. Проверьте, что файл GLB корректен.")); }
function showError(message) { loadingText.style.display = "none"; document.querySelector(".loader").style.display = "none"; errorMessage.textContent = message; errorMessage.style.display = "block"; setUploadStatus(message, true); }
const initialModelUrl = pageParams.get("model") || "./models/house.glb";
loader.load(initialModelUrl, ({ scene: model, animations }) => { house = model; prepare(model); fit(model); scene.add(model); if (animations.length) { mixer = new THREE.AnimationMixer(model); animations.forEach((c) => mixer.clipAction(c).play()); } loadingScreen.classList.add("hidden"); }, undefined, () => showError(pageParams.has("model") ? "Модель комнаты не загрузилась." : "Модель house.glb не найдена. Поместите её в папку models."));

function animate(position, target) { cameraAnimation = { start: performance.now(), from: camera.position.clone(), to: position.clone(), fromTarget: controls.target.clone(), toTarget: target.clone() }; }
$("home-button").onclick = () => animate(originalPosition, originalTarget); $("top-button").onclick = () => { if (!house) return; const s = new THREE.Box3().setFromObject(house).getSize(new THREE.Vector3()), d = Math.max(s.x, s.z); animate(new THREE.Vector3(.001, d * 1.7, .001), new THREE.Vector3()); };
$("rotate-button").onclick = (e) => { controls.autoRotate = !controls.autoRotate; controls.autoRotateSpeed = 1; e.currentTarget.classList.toggle("active", controls.autoRotate); }; $("walls-button").onclick = (e) => { wallsVisible = !wallsVisible; house?.traverse((o) => { if (o.isMesh && (o.userData.ifcType === "IfcWall" || o.name.toLowerCase().includes("wall") || o.name.toLowerCase().includes("стена"))) o.visible = wallsVisible; }); e.currentTarget.classList.toggle("active", wallsVisible); e.currentTarget.textContent = wallsVisible ? "Стены" : "Показать стены"; }; $("fullscreen-button").onclick = () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen();

const fileInput = $("model-file-input"), dropzone = $("upload-dropzone"), progress = $("upload-progress"), progressBar = progress.firstElementChild;
const setUploadStatus = (text, error = false) => { $("upload-status").textContent = text; $("upload-status").style.color = error ? "#ffb4b4" : ""; };
const showProgress = (value, indeterminate = false) => { progress.hidden = false; progress.classList.toggle("indeterminate", indeterminate); progressBar.style.width = `${value}%`; };
function describe(file) { return `${file.name} — ${(file.size / 1024 / 1024).toFixed(1)} МБ`; }
async function selectModel(file) { if (!file) return; const ext = file.name.split(".").pop().toLowerCase(); $("upload-file-info").textContent = describe(file); if (["pla", "pln"].includes(ext)) return setUploadStatus("Форматы PLA и PLN нельзя обработать непосредственно. Откройте проект в Archicad и сохраните его в формате IFC, затем загрузите IFC на сайт.", true); if (!['ifc', 'glb', 'gltf'].includes(ext)) return setUploadStatus("Выберите файл IFC, GLB или GLTF.", true); if (ext === "gltf") return setUploadStatus("Одиночный GLTF можно открыть только если все ресурсы встроены в файл. Для моделей с .bin и текстурами используйте GLB.", true); if (ext === "glb") { activeObjectUrl = URL.createObjectURL(file); loadModel(activeObjectUrl); return; } await uploadIfc(file); }
function uploadIfc(file) { const password = $("upload-password").value; if (!password) return setUploadStatus("Введите пароль для загрузки.", true); activeUpload = new XMLHttpRequest(); showProgress(0); $("upload-cancel").hidden = false; setUploadStatus("Загрузка файла"); activeUpload.open("POST", `${API_URL}/api/models`); activeUpload.setRequestHeader("X-Upload-Password", password); activeUpload.upload.onprogress = (e) => { if (e.lengthComputable) { const p = Math.round(e.loaded / e.total * 100); showProgress(p); setUploadStatus(`Загрузка файла: ${p}%`); } }; activeUpload.onerror = () => finishUpload("Не удалось связаться с сервером конвертации.", true); activeUpload.onabort = () => finishUpload("Загрузка отменена.", true); activeUpload.onload = () => { if (activeUpload.status >= 200 && activeUpload.status < 300) { try { pollJob(JSON.parse(activeUpload.responseText).jobId); } catch { finishUpload("Сервер вернул некорректный ответ.", true); } } else { try { finishUpload(JSON.parse(activeUpload.responseText).error || "Не удалось загрузить IFC.", true); } catch { finishUpload("Не удалось загрузить IFC.", true); } } }; const data = new FormData(); data.append("model", file); activeUpload.send(data); }
async function pollJob(jobId) { showProgress(0, true); const timer = setInterval(async () => { try { const response = await fetch(`${API_URL}/api/models/${encodeURIComponent(jobId)}/status`); const job = await response.json(); setUploadStatus(job.stage || "Обработка IFC"); if (job.status === "ready") { clearInterval(timer); progress.hidden = true; $("upload-cancel").hidden = true; loadModel(`${API_URL}${job.modelUrl}`); } else if (job.status === "failed") { clearInterval(timer); finishUpload(job.error || "Не удалось преобразовать IFC.", true); } } catch { clearInterval(timer); finishUpload("Не удалось получить статус обработки.", true); } }, 1000); }
function finishUpload(message, error) { progress.hidden = true; $("upload-cancel").hidden = true; activeUpload = null; setUploadStatus(message, error); }
$("upload-button").onclick = () => fileInput.click(); fileInput.onchange = () => selectModel(fileInput.files[0]); $("upload-cancel").onclick = () => activeUpload?.abort(); ["dragenter", "dragover"].forEach((t) => dropzone.addEventListener(t, (e) => { e.preventDefault(); dropzone.classList.add("dragging"); })); ["dragleave", "drop"].forEach((t) => dropzone.addEventListener(t, (e) => { e.preventDefault(); dropzone.classList.remove("dragging"); })); dropzone.addEventListener("drop", (e) => selectModel(e.dataTransfer.files[0]));

renderer.domElement.addEventListener("pointerdown", (e) => { const r = renderer.domElement.getBoundingClientRect(); pointer.set((e.clientX - r.left) / r.width * 2 - 1, -(e.clientY - r.top) / r.height * 2 + 1); raycaster.setFromCamera(pointer, camera); const hit = raycaster.intersectObjects(selectable, false)[0]; if (!hit) return roomCard.classList.remove("visible"); const d = hit.object.userData; if (d.ifcType !== "IfcSpace" && !d.title && !d.area) return roomCard.classList.remove("visible"); $("room-name").textContent = d.name || d.title || hit.object.name || "Помещение"; $("room-description").textContent = [d.area && `Площадь: ${d.area} м²`, d.ifcType].filter(Boolean).join(". "); roomCard.style.left = `${e.clientX}px`; roomCard.style.top = `${e.clientY}px`; roomCard.classList.add("visible"); });
addEventListener("resize", () => { camera.aspect = viewer.clientWidth / viewer.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(viewer.clientWidth, viewer.clientHeight, false); });
function render() { requestAnimationFrame(render); if (mixer) mixer.update(clock.getDelta()); if (cameraAnimation) { const p = Math.min((performance.now() - cameraAnimation.start) / 900, 1), e = 1 - (1 - p) ** 3; camera.position.lerpVectors(cameraAnimation.from, cameraAnimation.to, e); controls.target.lerpVectors(cameraAnimation.fromTarget, cameraAnimation.toTarget, e); if (p === 1) cameraAnimation = null; } controls.update(); renderer.render(scene, camera); } render();
