(() => {
  const API = window.HouseConfig?.apiBaseUrl || location.origin;
  const main = document.querySelector("#project-main"), id = new URLSearchParams(location.search).get("id");
  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
  const request = async (path, options = {}) => { const response = await fetch(`${API}${path}`, { ...options, credentials: "include", headers: options.body instanceof FormData ? undefined : { "Content-Type": "application/json", ...(options.headers || {}) } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || "Не удалось выполнить запрос."); return body; };
  async function render() {
    const [{ user }, project] = await Promise.all([request("/api/auth/me"), request(`/api/projects/${encodeURIComponent(id)}`)]);
    window.createProfileMenu(document.querySelector("#profile-menu-host"), user, API);
    document.title = `${project.name} — House Reviewer`;
    main.innerHTML = `<section class="studio-shell project-editor"><div class="studio-eyebrow"><p>Проект / ${esc(project.status)}</p><a href="./studio.html?view=projects">Все проекты ×</a></div><div class="project-editor-head"><div><p class="kicker">Страница отдельного объекта</p><h1>${esc(project.name)}</h1><p>Настройте страницу, которую увидят заказчик и команда проекта.</p></div><a class="button-secondary" href="./viewer.html?project=${project.id}${project.modelUrl ? `&model=${encodeURIComponent(API + project.modelUrl)}` : ""}" target="_blank">Предпросмотр ↗</a></div><div class="project-editor-grid"><form id="project-settings" class="project-settings"><p class="kicker">Основные данные</p><label>Название комплекса или объекта<input name="name" value="${esc(project.name)}" minlength="2" maxlength="100" required></label><div class="project-fields"><label>Площадь, м²<input name="area" type="number" min="1" value="${project.area}" required></label><label>Помещения<input name="rooms" type="number" min="1" value="${project.rooms}" required></label></div><label>Оформление<select name="theme"><option ${project.theme === "Тёплый" ? "selected" : ""}>Тёплый</option><option ${project.theme === "Ночной" ? "selected" : ""}>Ночной</option><option ${project.theme === "Нейтральный" ? "selected" : ""}>Нейтральный</option></select></label><button class="button" type="submit">Сохранить изменения <span>→</span></button><p class="form-status" id="settings-status"></p></form><form id="model-upload" class="model-editor"><p class="kicker">3D-модель проекта</p><div class="model-state"><strong>${project.modelUrl ? "Модель загружена" : "Модель ещё не добавлена"}</strong><p>${project.modelUrl ? "Новая загрузка заменит текущую модель." : "Используйте единый GLB-файл со встроенными материалами."}</p></div><label class="file-drop"><input name="model" type="file" accept=".glb" required><span><strong>Выберите GLB-модель</strong><p>до 200 МБ</p></span></label><button class="button-secondary" type="submit">Загрузить модель</button><p class="form-status" id="model-status"></p></form></div></section>`;
    document.querySelector("#project-settings").onsubmit = async (event) => { event.preventDefault(); const button = event.currentTarget.querySelector("button"), status = document.querySelector("#settings-status"); button.disabled = true; status.textContent = ""; try { const data = Object.fromEntries(new FormData(event.currentTarget)); await request(`/api/projects/${id}`, { method: "PATCH", body: JSON.stringify(data) }); status.classList.add("success"); status.textContent = "Изменения сохранены."; setTimeout(render, 500); } catch (error) { status.textContent = error.message; button.disabled = false; } };
    document.querySelector("#model-upload").onsubmit = async (event) => { event.preventDefault(); const button = event.currentTarget.querySelector("button"), status = document.querySelector("#model-status"), data = new FormData(event.currentTarget); button.disabled = true; status.textContent = "Загрузка модели…"; try { await request(`/api/projects/${id}/model`, { method: "POST", body: data }); status.classList.add("success"); status.textContent = "Модель загружена."; setTimeout(render, 500); } catch (error) { status.textContent = error.message; button.disabled = false; } };
  }
  render().catch((error) => { if (error.message === "Требуется вход.") location.replace("./auth.html"); else main.innerHTML = `<section class="studio-shell empty-projects"><h1>Проект не найден</h1><p>${esc(error.message)}</p><a class="button" href="./studio.html?view=projects">К проектам <span>→</span></a></section>`; }).finally(() => main.removeAttribute("aria-busy"));
})();
