(() => {
  document.querySelectorAll("svg.icon").forEach((icon) => { icon.setAttribute("viewBox", "0 0 24 24"); icon.setAttribute("aria-hidden", "true"); });
  if (new URLSearchParams(location.search).has("preview")) return;
  const API_URL = window.MODEL_API_URL || "http://localhost:3001"; let rooms = window.HOUSE_ROOMS, roomBySlug = {}, roomById = {};
  const indexRooms = () => { roomBySlug = Object.fromEntries(rooms.map((room) => [room.slug, room])); roomById = Object.fromEntries(rooms.map((room) => [room.id, room])); }; indexRooms();
  const page = document.getElementById("room-page"), content = document.getElementById("room-content"), sidebar = document.getElementById("rooms-sidebar");
  sidebar.prepend(document.querySelector(".tools"));
  let manifests = {}, notes = [], selectedRoom = null, selectedTab = "overview", photoFilter = "all", selectedFiles = [];
  const absolute = (url) => url ? `${API_URL}${url}` : "./images/room-placeholder.svg";
  const typeLabels = { construction:"Ход строительства", completed:"Готовая работа", defect:"Замечание", control:"Контрольный снимок", other:"Другое" };
  const currentRoute = () => new URLSearchParams(location.search).get("route") || (window.top.location.pathname.startsWith("/rooms/") ? window.top.location.pathname : "");
  const navigate = (path, replace = false) => { const history = window.top.history; history[replace ? "replaceState" : "pushState"]({}, "", path); if (path.startsWith("/rooms/")) openRoom(roomBySlug[path.split("/")[2]], false); else closeRoom(false); };

  async function loadData() {
    try { const catalogResponse = await fetch(`${API_URL}/api/rooms`, { cache:"no-store" }); if (catalogResponse.ok) { rooms = await catalogResponse.json(); indexRooms(); window.HOUSE_ROOMS = rooms; const routeSlug = currentRoute().split("/")[2]; if (!selectedRoom && routeSlug && roomBySlug[routeSlug]) openRoom(roomBySlug[routeSlug], false); } } catch { /* Используем встроенный список, если API временно недоступен. */ }
    const results = await Promise.all(rooms.map(async (room) => { try { const response = await fetch(`${API_URL}/api/rooms/${room.id}`, { cache:"no-store" }); return [room.id, response.ok ? await response.json() : {}]; } catch { return [room.id, {}]; } }));
    manifests = Object.fromEntries(results);
    try { const response = await fetch(`${API_URL}/api/notes`, { cache:"no-store" }); notes = response.ok ? await response.json() : []; } catch { notes = []; }
    renderSidebar(); if (selectedRoom) renderRoom();
  }
  function roomCounts(room) { const data = manifests[room.id] || {}, roomNotes = notes.filter((note) => note.roomId === room.id); return { photos:(data.photos || []).length, notes:roomNotes.length }; }
  function roomIcon(room) { if (room.icon) return room.icon; const value = `${room.id} ${room.name}`.toLowerCase(); if (/kitchen|кух/.test(value)) return "🍳"; if (/bed|спаль|детск/.test(value)) return "🛏️"; if (/bath|сануз|ванн|туал/.test(value)) return "🚿"; if (/hall|прихож|корид/.test(value)) return "🚪"; if (/balcon|terrace|балкон|террас/.test(value)) return "🌿"; if (/living|гостин/.test(value)) return "🛋️"; if (/office|кабин/.test(value)) return "💻"; return "🏠"; }
  function renderSidebar() {
    document.getElementById("room-links").innerHTML = `<button class="room-link ${selectedRoom ? "" : "active"}" data-go-home><span class="room-link-icon">🏢</span><span class="room-link-copy"><strong>Все помещения</strong><small>Общая 3D-модель</small></span></button>${rooms.map((room) => { const count = roomCounts(room); return `<button class="room-link ${selectedRoom?.id === room.id ? "active" : ""}" data-open-room="${room.slug}"><span class="room-link-icon">${roomIcon(room)}</span><span class="room-link-copy"><strong>${room.name}</strong><small>${count.photos} фото · ${count.notes} замечаний →</small></span></button>`; }).join("")}`;
  }
  function openRoom(room, updateUrl = true) { if (!room) return navigate("/", true); selectedRoom = room; window.NOTE_ROOM_ID = room.id; selectedTab = "overview"; page.classList.add("active"); sidebar.classList.remove("open"); document.querySelector(".project-card").hidden = true; document.querySelector(".tools").hidden = true; if (updateUrl) window.top.history.pushState({}, "", `/rooms/${room.slug}`); renderSidebar(); renderRoom(); }
  function closeRoom(updateUrl = true, preserveNoteRoom = false) { selectedRoom = null; if (!preserveNoteRoom) window.NOTE_ROOM_ID = null; page.classList.remove("active"); const in3d = Boolean(document.querySelector('[data-mode="3d"].active')); document.querySelector(".project-card").hidden = !in3d; document.querySelector(".tools").hidden = !in3d; if (updateUrl) window.top.history.pushState({}, "", "/"); renderSidebar(); }
  function updatedAt(data) { const values = [...(data.photos || []).map((photo) => photo.createdAt)]; return values.sort().at(-1) || null; }
  function renderRoom() {
    const data = manifests[selectedRoom.id] || {}, count = roomCounts(selectedRoom), updated = updatedAt(data);
    document.getElementById("room-page-title").textContent = selectedRoom.name; document.getElementById("room-breadcrumbs").textContent = `Главная / ${selectedRoom.name}`;
    document.getElementById("room-stats").innerHTML = `<span>${selectedRoom.area} м²</span><span>${count.photos} фото</span><span>${count.notes} замечаний</span><span>${updated ? `Обновлено ${new Date(updated).toLocaleDateString("ru")}` : "Материалы не обновлялись"}</span>`;
    document.querySelectorAll("[data-room-tab]").forEach((button) => button.classList.toggle("active", button.dataset.roomTab === selectedTab)); renderTab(data);
  }
  function photoCards(photos) { return photos.length ? `<div class="gallery-grid">${photos.map((photo) => `<button class="gallery-card" data-image="${absolute(photo.url)}" data-caption="${typeLabels[photo.type] || "Фото"} · ${photo.date}"><img src="${absolute(photo.thumbnailUrl || photo.url)}" alt="${photo.comment || selectedRoom.name}" loading="lazy"><span>${typeLabels[photo.type] || "Фото"}<small style="display:block;color:#64748b;margin-top:4px">${photo.date}${photo.comment ? ` · ${photo.comment}` : ""}</small></span></button>`).join("")}</div>` : `<div class="empty-state">В этой комнате пока нет фотографий.</div>`; }
  function renderTab(data) {
    const roomNotes = notes.filter((note) => note.roomId === selectedRoom.id), photos = data.photos || [];
    if (selectedTab === "overview") { const hero = absolute(photos[0]?.url || data.renderUrls?.[0] || data.floorplanUrl); content.innerHTML = `<div class="overview-grid"><article class="overview-card overview-hero"><img src="${hero}" alt="${selectedRoom.name}"><button class="primary" data-select-room-tab="3d">Показать в 3D</button></article><div style="display:grid;gap:16px"><article class="overview-card"><h3>Материалы</h3><p>${photos.length} фото · ${(data.renderUrls || []).length} рендеров</p><button class="primary" data-open-photo-upload>Загрузить фото</button></article><article class="overview-card"><h3>Замечания</h3><p>${roomNotes.length} связанных замечаний</p><button class="secondary" data-select-room-tab="notes">Открыть заметки</button></article></div></div>`; }
    if (selectedTab === "3d") { content.innerHTML = `<div class="photo-toolbar"><button class="secondary" data-go-home>Вернуться к общей модели</button><button class="primary" data-upload-room-model>${data.modelUrl ? "Заменить 3D-модель" : "Загрузить 3D-модель"}</button></div>${data.modelUrl ? `<iframe class="room-model-frame" src="./viewer.html?preview=1&room=${encodeURIComponent(selectedRoom.id)}&model=${encodeURIComponent(absolute(data.modelUrl))}" title="3D: ${selectedRoom.name}"></iframe>` : `<div class="empty-state"><strong style="display:block;margin-bottom:8px;color:#111827">3D-модель помещения не загружена</strong><span>Нажмите «Загрузить 3D-модель» и выберите файл GLB.</span></div>`}`; }
    if (selectedTab === "photos") { const filtered = photoFilter === "all" ? photos : photos.filter((photo) => photo.type === photoFilter); content.innerHTML = `<div class="photo-toolbar"><h2>Фотографии</h2><button class="primary" data-open-photo-upload>Загрузить фото</button></div><div class="photo-filters">${[["all","Все"],["construction","Ход строительства"],["completed","Готовая работа"],["defect","Замечания"],["control","Контрольные"]].map(([id,label]) => `<button class="photo-filter ${photoFilter === id ? "active" : ""}" data-photo-filter="${id}">${label}</button>`).join("")}</div>${photoCards(filtered)}`; }
    if (selectedTab === "renders") content.innerHTML = `<div class="photo-toolbar"><h2>Рендеры</h2><button class="primary" data-open-render-upload>Загрузить рендер</button></div>${(data.renderUrls || []).length ? `<div class="gallery-grid">${data.renderUrls.map((url,index) => `<button class="gallery-card" data-image="${absolute(url)}" data-caption="${selectedRoom.name} · рендер ${index+1}"><img src="${absolute(url)}" alt="Рендер ${index+1}"><span>Рендер ${index+1}</span></button>`).join("")}</div>` : `<div class="empty-state">Рендеры ещё не загружены.</div>`}`;
    if (selectedTab === "notes") content.innerHTML = `<div class="photo-toolbar"><h2>Заметки комнаты</h2><button class="primary" data-global-notes>Добавить заметку</button></div>${roomNotes.length ? roomNotes.map((note) => `<article class="overview-card" style="margin-bottom:10px"><strong>${note.text}</strong><p class="status">${new Date(note.createdAt).toLocaleString("ru")} · Новая</p></article>`).join("") : `<div class="empty-state">Для комнаты пока нет связанных заметок.</div>`}`;
    if (selectedTab === "documents") content.innerHTML = `<div class="photo-toolbar"><h2>Документы комнаты</h2></div><div class="empty-state">API документов помещения пока не подключён. IFC и GLB доступны в общем разделе «Документы».</div>`;
  }
  document.addEventListener("click", (event) => {
    const roomLink = event.target.closest("[data-open-room]"); if (roomLink) return openRoom(roomBySlug[roomLink.dataset.openRoom]);
    if (event.target.closest("[data-go-home]")) return closeRoom();
    const tab = event.target.closest("[data-room-tab],[data-select-room-tab]"); if (tab && selectedRoom) { selectedTab = tab.dataset.roomTab || tab.dataset.selectRoomTab; renderRoom(); if (selectedTab === "3d") window.focusRoom?.(selectedRoom.id); return; }
    const filter = event.target.closest("[data-photo-filter]"); if (filter) { photoFilter = filter.dataset.photoFilter; renderRoom(); return; }
    if (event.target.closest("[data-open-photo-upload]")) openUpload();
    if (event.target.closest("[data-open-render-upload]")) renderFilesInput.click();
    if (event.target.closest("[data-upload-room-model]")) roomModelInput.click();
    if (event.target.closest("[data-global-notes]")) { closeRoom(false, true); document.querySelector('[data-mode="notes"]').click(); }
    if (selectedRoom && event.target.closest("[data-mode]")) closeRoom(false);
  });
  document.getElementById("room-back").onclick = () => closeRoom(); document.querySelector(".brand").style.cursor = "pointer"; document.querySelector(".brand").onclick = () => closeRoom();
  document.getElementById("rooms-mobile-button").onclick = () => sidebar.classList.toggle("open"); document.getElementById("rooms-collapse").onclick = () => { sidebar.classList.toggle("collapsed"); localStorage.setItem("roomsCollapsed", sidebar.classList.contains("collapsed") ? "1" : "0"); }; if (localStorage.getItem("roomsCollapsed") === "1") sidebar.classList.add("collapsed");
  const addRoomModal = document.getElementById("add-room-modal"), addRoomForm = document.getElementById("add-room-form"), roomIcons = ["🏠","🛋️","🛏️","🍳","🚿","🚪","💻","🌿"];
  document.getElementById("new-room-icons").innerHTML = roomIcons.map((icon,index) => `<button class="icon-choice ${index === 0 ? "selected" : ""}" type="button" role="radio" aria-checked="${index === 0}" data-room-icon="${icon}">${icon}</button>`).join("");
  document.getElementById("new-room-icons").onclick = (event) => { const choice = event.target.closest("[data-room-icon]"); if (!choice) return; document.getElementById("new-room-icon").value = choice.dataset.roomIcon; document.querySelectorAll("[data-room-icon]").forEach((button) => { const selected = button === choice; button.classList.toggle("selected", selected); button.setAttribute("aria-checked", selected); }); };
  document.getElementById("add-room-button").onclick = () => { addRoomForm.reset(); document.getElementById("new-room-icon").value = "🏠"; document.getElementById("add-room-state").textContent = ""; document.querySelectorAll("[data-room-icon]").forEach((button,index) => { button.classList.toggle("selected", index === 0); button.setAttribute("aria-checked", index === 0); }); addRoomModal.showModal(); document.getElementById("new-room-name").focus(); };
  document.getElementById("add-room-cancel").onclick = () => addRoomModal.close();
  addRoomForm.onsubmit = async (event) => { event.preventDefault(); const name = document.getElementById("new-room-name").value.trim(), area = Number(document.getElementById("new-room-area").value), icon = document.getElementById("new-room-icon").value, password = document.getElementById("new-room-password").value, state = document.getElementById("add-room-state"), submit = document.getElementById("add-room-submit"); if (!name || !Number.isFinite(area) || area < 0) return state.textContent = "Укажите название и корректную площадь."; submit.disabled = true; state.textContent = "Добавляем помещение…"; try { const response = await fetch(`${API_URL}/api/rooms`, { method:"POST", headers:{ "Content-Type":"application/json", "X-Upload-Password":password }, body:JSON.stringify({ name, area, icon }) }); const room = await response.json(); if (!response.ok) throw new Error(room.error || "Не удалось добавить помещение."); rooms.push(room); indexRooms(); manifests[room.id] = { photos:[], renderUrls:[] }; addRoomModal.close(); renderSidebar(); openRoom(room); } catch (error) { state.textContent = error.message || "Потеря соединения."; } finally { submit.disabled = false; } };

  const modal = document.getElementById("photo-upload-modal"), filesInput = document.getElementById("photo-files"), drop = document.getElementById("photo-drop");
  const renderFilesInput = document.createElement("input"); renderFilesInput.type = "file"; renderFilesInput.accept = "image/jpeg,image/png,image/webp"; renderFilesInput.multiple = true; renderFilesInput.hidden = true; document.body.append(renderFilesInput);
  const roomModelInput = document.createElement("input"); roomModelInput.type = "file"; roomModelInput.accept = ".glb,model/gltf-binary"; roomModelInput.hidden = true; document.body.append(roomModelInput);
  function openUpload() { selectedFiles = []; renderPreviews(); document.getElementById("upload-room-label").textContent = `Помещение: ${selectedRoom.name}`; document.getElementById("photo-date").value = new Date().toISOString().slice(0,10); document.getElementById("photo-upload-state").textContent = ""; modal.showModal(); }
  function addFiles(files) { const allowed = new Set(["image/jpeg","image/png","image/webp"]), valid = [...files].filter((file) => allowed.has(file.type) && file.size <= 200*1024*1024); selectedFiles.push(...valid); document.getElementById("photo-upload-state").textContent = valid.length === files.length ? `Выбрано файлов: ${selectedFiles.length}` : "Некоторые файлы имеют неподдерживаемый формат или слишком большой размер."; renderPreviews(); }
  function renderPreviews() { document.getElementById("photo-previews").innerHTML = selectedFiles.map((file,index) => `<div class="photo-preview"><img src="${URL.createObjectURL(file)}" alt="${file.name}"><button class="preview-remove" type="button" data-remove-preview="${index}">×</button></div>`).join(""); }
  drop.onclick = () => filesInput.click(); filesInput.onchange = () => addFiles(filesInput.files); ["dragenter","dragover"].forEach((type) => drop.addEventListener(type,(event)=>{event.preventDefault();drop.classList.add("dragging");})); ["dragleave","drop"].forEach((type)=>drop.addEventListener(type,(event)=>{event.preventDefault();drop.classList.remove("dragging");})); drop.addEventListener("drop",(event)=>addFiles(event.dataTransfer.files));
  document.getElementById("photo-previews").onclick = (event) => { const button = event.target.closest("[data-remove-preview]"); if (!button) return; selectedFiles.splice(Number(button.dataset.removePreview),1); renderPreviews(); };
  document.getElementById("photo-upload-cancel").onclick = () => modal.close();
  function uploadPhoto(data, password, index, total) { return new Promise((resolve, reject) => { const request = new XMLHttpRequest(); request.open("POST", `${API_URL}/api/rooms/${selectedRoom.id}/assets/photo`); request.setRequestHeader("X-Upload-Password", password); request.upload.onprogress = (event) => { if (event.lengthComputable) document.getElementById("photo-upload-state").textContent = `Файл ${index + 1} из ${total}: ${Math.round(event.loaded / event.total * 100)}%`; }; request.onerror = () => reject(new Error("Потеря соединения.")); request.onload = () => { let result; try { result = JSON.parse(request.responseText); } catch { return reject(new Error("Сервер вернул некорректный ответ.")); } request.status >= 200 && request.status < 300 ? resolve(result) : reject(new Error(result.error || "Ошибка загрузки.")); }; request.send(data); }); }
  renderFilesInput.onchange = async () => { const files = [...renderFilesInput.files], allowed = new Set(["image/jpeg","image/png","image/webp"]); if (!files.length) return; if (files.some((file) => !allowed.has(file.type) || file.size > 200*1024*1024)) { alert("Используйте JPG, PNG или WEBP размером до 200 МБ."); renderFilesInput.value = ""; return; } const password = prompt("Введите пароль для загрузки рендеров:") || ""; if (!password) { renderFilesInput.value = ""; return; } try { for (let index=0; index<files.length; index++) { const data = new FormData(); data.append("file",files[index]); const response = await fetch(`${API_URL}/api/rooms/${selectedRoom.id}/assets/render`,{method:"POST",headers:{"X-Upload-Password":password},body:data}); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Не удалось загрузить рендер."); manifests[selectedRoom.id] = result; } renderRoom(); renderSidebar(); showToast(`Загружено рендеров: ${files.length}`); } catch(error) { alert(error.message || "Потеря соединения."); } finally { renderFilesInput.value = ""; } };
  roomModelInput.onchange = async () => { const file = roomModelInput.files[0]; if (!file) return; if (!file.name.toLowerCase().endsWith(".glb")) { alert("Для комнаты нужен файл GLB."); roomModelInput.value = ""; return; } const password = prompt("Введите пароль для загрузки 3D-модели комнаты:") || ""; if (!password) { roomModelInput.value = ""; return; } try { const data = new FormData(); data.append("file",file); const response = await fetch(`${API_URL}/api/rooms/${selectedRoom.id}/assets/model`,{method:"POST",headers:{"X-Upload-Password":password},body:data}); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Не удалось загрузить модель."); manifests[selectedRoom.id] = result; renderRoom(); showToast("3D-модель комнаты загружена"); } catch(error) { alert(error.message || "Потеря соединения."); } finally { roomModelInput.value = ""; } };
  document.getElementById("photo-upload-form").onsubmit = async (event) => { event.preventDefault(); const state = document.getElementById("photo-upload-state"), submit = document.getElementById("photo-upload-submit"); if (!selectedFiles.length) return state.textContent = "Выберите хотя бы одно фото."; const password = prompt("Введите пароль для загрузки фотографий:") || ""; if (!password) return state.textContent = "Загрузка отменена: пароль не введён."; submit.disabled = true; try { for (let index=0; index<selectedFiles.length; index++) { const data = new FormData(); data.append("file",selectedFiles[index]); data.append("type",document.getElementById("photo-type").value); data.append("date",document.getElementById("photo-date").value); data.append("comment",document.getElementById("photo-comment").value); manifests[selectedRoom.id] = await uploadPhoto(data, password, index, selectedFiles.length); } modal.close(); renderSidebar(); renderRoom(); showToast(`Загружено фото: ${selectedFiles.length}`); } catch(error) { state.textContent = error.message === "Неверный пароль для загрузки." ? "Неверный пароль." : error.message || "Потеря соединения."; } finally { submit.disabled=false; } };
  function showToast(text) { const toast=document.createElement("div"); toast.textContent=text; Object.assign(toast.style,{position:"fixed",zIndex:200,right:"20px",bottom:"20px",padding:"12px 16px",color:"white",background:"#16a34a",borderRadius:"12px",boxShadow:"0 12px 30px #0002"}); document.body.append(toast); setTimeout(()=>toast.remove(),2800); }
  try { window.top.addEventListener("popstate",()=>{ const path=window.top.location.pathname; if(path.startsWith("/rooms/")) openRoom(roomBySlug[path.split("/")[2]],false); else closeRoom(false); }); } catch {}
  const route = currentRoute(); if (route.startsWith("/rooms/")) selectedRoom = roomBySlug[route.split("/")[2]] || null; if (selectedRoom) openRoom(selectedRoom,false); loadData();
})();
