(() => {
  const { request, user } = window.studioContext, main = document.querySelector("#studio-main");
  const $ = (selector, root = document) => root.querySelector(selector), $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
  const view = new URLSearchParams(location.search).get("view") || "dashboard";
  $$('[data-studio-nav]').forEach((link) => link.classList.toggle("active", link.dataset.studioNav === view));
  $$('.studio-mobile-nav a').forEach((link) => link.classList.toggle("active", link.href === location.href || (view === "dashboard" && link.href.includes("view=projects"))));
  const projectCard = (project) => `<a class="project-row" href="./project.html?id=${encodeURIComponent(project.id)}"><img src="./images/editorial-house.webp" alt=""><div><h3>${esc(project.name)}</h3><p>${project.area} м² · ${project.rooms} комнат</p></div><small>${new Date(project.updatedAt).toLocaleDateString("ru")}</small><span class="status-dot">${esc(project.status)}</span><span class="row-arrow">→</span></a>`;
  async function dashboard() { const projects = await request("/api/projects"), project = projects[0]; main.innerHTML = `<section class="studio-shell"><div class="studio-eyebrow"><p>Рабочее пространство / ${new Date().toLocaleDateString("ru", { month: "long", year: "numeric" })}</p><a class="button button-small" href="?view=new">Новый проект <span>＋</span></a></div><h1 class="studio-title">Добрый день, ${esc(user.name.split(" ")[0])}.<br><em>Продолжим работу?</em></h1>${project ? `<div class="dashboard-grid"><a class="project-feature" href="./project.html?id=${project.id}"><img src="./images/editorial-house.webp" alt=""><div class="project-feature-content"><p class="kicker light">Последний проект</p><h2>${esc(project.name)}</h2><div class="project-meta-line"><span>${project.area} м²</span><span>${project.rooms} комнат</span><span>${esc(project.status)}</span></div></div></a><aside class="dashboard-aside"><h3>Проект остаётся живым</h3><p>Редактируйте данные и модель на отдельной странице объекта.</p></aside></div>` : `<div class="empty-projects"><h2>Создайте первый проект</h2><a class="button" href="?view=new">Начать <span>→</span></a></div>`}</section>`; }
  async function list() { const projects = await request("/api/projects"); main.innerHTML = `<section class="studio-shell"><div class="studio-eyebrow"><p>Все объекты / ${projects.length}</p><a class="button button-small" href="?view=new">Создать проект <span>＋</span></a></div><h1 class="studio-title">Ваши <em>проекты</em></h1>${projects.length ? `<div class="projects-list">${projects.map(projectCard).join("")}</div>` : '<div class="empty-projects"><p>Здесь появятся ваши объекты.</p></div>'}</section>`; }
  function wizard() { let step = 1, data = { name: "", area: "", rooms: "", theme: "Тёплый" }; const draw = () => { const titles = ["Расскажите об объекте", "Выберите настроение", "Проверьте детали"]; main.innerHTML = `<section class="studio-shell"><div class="studio-eyebrow"><p>Новый проект / шаг ${step} из 3</p><a href="?view=projects">Закрыть ×</a></div><div class="wizard"><ol class="wizard-steps">${["Объект", "Оформление", "Создание"].map((label, index) => `<li class="${index + 1 === step ? "active" : ""}"><span>${index + 1}</span>${label}</li>`).join("")}</ol><div class="wizard-main"><p class="kicker">Шаг 0${step}</p><h1>${titles[step - 1]}</h1><form id="wizard-form">${step === 1 ? `<div class="wizard-form"><label class="full">Название комплекса или объекта<input name="name" value="${esc(data.name)}" required minlength="2" placeholder="Дом у сосен"></label><label>Площадь, м²<input name="area" type="number" min="1" value="${esc(data.area)}" required></label><label>Количество помещений<input name="rooms" type="number" min="1" value="${esc(data.rooms)}" required></label></div>` : step === 2 ? `<div class="theme-choices">${["Тёплый", "Ночной", "Нейтральный"].map((theme) => `<button type="button" data-theme="${theme}" class="theme-choice ${data.theme === theme ? "active" : ""}"><span class="theme-swatch"></span><strong>${theme}</strong></button>`).join("")}</div>` : `<div class="review-sheet"><dl><div><dt>Объект</dt><dd>${esc(data.name)}</dd></div><div><dt>Площадь</dt><dd>${esc(data.area)} м²</dd></div><div><dt>Комнаты</dt><dd>${esc(data.rooms)}</dd></div><div><dt>Оформление</dt><dd>${esc(data.theme)}</dd></div></dl></div>`}</form><p class="form-status" id="wizard-status"></p><div class="wizard-actions">${step > 1 ? '<button class="button-secondary" id="wizard-back">← Назад</button>' : "<span></span>"}<button class="button" id="wizard-next">${step === 3 ? "Создать проект" : "Продолжить"} <span>→</span></button></div></div></div></section>`; $$('[data-theme]').forEach((button) => button.onclick = () => { data.theme = button.dataset.theme; draw(); }); $("#wizard-back")?.addEventListener("click", () => { step--; draw(); }); $("#wizard-next").onclick = async (event) => { if (step === 1) { const form = $("#wizard-form"); if (!form.reportValidity()) return; data = { ...data, name: form.name.value, area: Number(form.area.value), rooms: Number(form.rooms.value) }; } if (step < 3) { step++; draw(); return; } event.currentTarget.disabled = true; try { const project = await request("/api/projects", { method: "POST", body: JSON.stringify(data) }); location.href = `./project.html?id=${project.id}`; } catch (error) { $("#wizard-status").textContent = error.message; event.currentTarget.disabled = false; } }; }; draw(); }
  function billing() { main.innerHTML = `<section class="studio-shell"><div class="studio-eyebrow"><p>Аккаунт / Оплата</p></div><h1 class="studio-title">Тариф и <em>оплата</em></h1><div class="billing-card"><p class="kicker">Текущий тариф</p><h2>Пробный доступ</h2><p>Платёжная система пока не подключена. Здесь появятся тариф, история платежей и реквизиты.</p><button class="button" disabled>Выбрать тариф <span>→</span></button></div></section>`; }
  const result = (view === "projects" ? list : view === "new" ? wizard : view === "billing" ? billing : dashboard)();
  if (result?.catch) result.catch((error) => { main.innerHTML = `<section class="studio-shell"><p class="form-status">${esc(error.message)}</p></section>`; });
})();
